vehicle:
 vehicle_description:
  robotNamespace: hmmwv
  robotName: hmmwv
  frameName: map
  ground_truth_topic: base_pose_ground_truth

  # mesh parameters
  scale_factor: 0.2
  mesh_mode: 1

  # vehicle geometry
  base_link: base_link
  base_width: 1.9
  base_length: 3.3
  base_height: 1.2
  base_clearance: 0.5

  # wheels
  wheel_radius: 0.393
  wheel_width: 0.1
  wheel_mass: 2.5
  la: 1.6
  lb: 1.7
  wheel_base: 1
  mu1: 0.9
  mu2: 0.9
  minDepth: 0.005
  kp: 1e8

  # LiDAR properties
  lidar_z: 1.4
  lidar_x: 1.75
  topic: lidar_points
