system:
 vehicle_description:
  flags:
   postion_update_external: true
   lidar_initialized: false
   obstacles_initialized: false
 chrono:
  namespace: chrono
  flags:
    initialized: false
    gui: true
 ros_base_planner:
  namespace: ros_base_planner
  flags:
   initialized: false
 planner:
  namespace: vehicle/chrono/default
