---
planner:
  nloptcontrol_planner:
    misc:
      EP: NaN
      FixedTp: true
      L_rd: 5.0
      Lr: 50.0
      N: 20
      Nck: NaN
      PredictX0: true
      Xlims: [111, 250]
      Ylims: [-1, 140]
      finalTimeDV: true
      integrationScheme: bkwEuler
      model: ThreeDOFv2
      mpc_max_iter: 60
      sm: 4.5
      sm2: 3.0
      solver: KNITRO
      tex: 0.5
      tfMax: 10
      tp: NaN
    solver:
      acceptable_compl_inf_tol: 0.01
      acceptable_constr_viol_tol: 0.01
      acceptable_dual_inf_tol: 1e+10
      acceptable_obj_change_tol: 1e+20
      acceptable_tol: 1e-2
      compl_inf_tol: 1e-1
      diverging_iterates_tol: 1e+20
      dual_inf_tol: 5.0
      feastol: 1.0e+20
      feastol_abs: 7e-2
      ftol: 1e-15
      ftol_iters: 5
      infeastol: 1e-2
      maxfevals: -1
      maxit: 500
      maxtime_cpu: 30.0
      maxtime_real: 30.0
      opttol: 1e+20
      opttol_abs: 5e-1
      outlev: 0
      warm_start_init_point: true
      xtol: 1e-12
    tolerances:
      fax: NaN
      fpsi: NaN
      fr: NaN
      fsa: NaN
      fu: NaN
      fv: NaN
      fx: 1.0
      fy: 1.0
      iax: 0.05
      ipsi: 0.01
      ir: 0.05
      isa: 0.001
      iu: 0.05
      iv: 0.05
      ix: 0.05
      iy: 0.05
    weights:
      Fz: 0.1
      ce: 1.0
      driver: 1.0
      goal: 100.0
      haf: 1.0e-05
      jx: 0.01
      path: 1.0
      psi: 0.01
      sa: 0.1
      sr: 1.0
      time: 0.05
