#Setting the "rolling_window" parameter to true means that the costmap will
#remain centered around the robot as the robot moves through the world.
#The "width," "height," and "resolution" parameters set the width (meters),
#height (meters), and resolution (meters/cell) of the costmap.
local_costmap:
  global_frame: /map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 15
  height: 15
  resolution: 0.05
